require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ChoreographyNote' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  pod 'RNSound', :path => '../node_modules/react-native-sound'






  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  target 'ChoreographyNoteTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChoreographyNote-tvOS' do
  # Pods for ChoreographyNote-tvOS

  target 'ChoreographyNote-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
